# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 478)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.sAWC = QtWidgets.QWidget()
        self.sAWC.setGeometry(QtCore.QRect(0, 0, 570, 386))
        self.sAWC.setObjectName("sAWC")
        self.gridLayout = QtWidgets.QGridLayout(self.sAWC)
        self.gridLayout.setObjectName("gridLayout")
        self.vSB = QtWidgets.QScrollBar(self.sAWC)
        self.vSB.setOrientation(QtCore.Qt.Vertical)
        self.vSB.setObjectName("vSB")
        self.gridLayout.addWidget(self.vSB, 0, 1, 1, 1)
        self.tW = QtWidgets.QTableWidget(self.sAWC)
        self.tW.setObjectName("tW")
        self.tW.setColumnCount(0)
        self.tW.setRowCount(0)
        self.gridLayout.addWidget(self.tW, 0, 0, 1, 1)
        self.hSB = QtWidgets.QScrollBar(self.sAWC)
        self.hSB.setOrientation(QtCore.Qt.Horizontal)
        self.hSB.setObjectName("hSB")
        self.gridLayout.addWidget(self.hSB, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.sAWC)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 3)
        self.pB_Plus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Plus.sizePolicy().hasHeightForWidth())
        self.pB_Plus.setSizePolicy(sizePolicy)
        self.pB_Plus.setText("")
        self.pB_Plus.setObjectName("pB_Plus")
        self.gridLayout_2.addWidget(self.pB_Plus, 1, 0, 1, 1)
        self.pB_Minus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Minus.sizePolicy().hasHeightForWidth())
        self.pB_Minus.setSizePolicy(sizePolicy)
        self.pB_Minus.setText("")
        self.pB_Minus.setObjectName("pB_Minus")
        self.gridLayout_2.addWidget(self.pB_Minus, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(489, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
